services:
  codey-bot:
    image: codey-bootcamp:latest
    container_name: codey-bootcamp
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
      - ./db:/usr/app/db
