services:
  codey-bot:
    image: uwcsclub/codey-bootcamp:${TAG}
    container_name: codey-bootcamp-production
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/usr/app/logs
      - ./db:/usr/app/db
    logging:
      driver: gcplogs
      