name: Deploy Codey Bootcamp

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-to: uwcsclub/codey-bootcamp:cache
          cache-from: uwcsclub/codey-bootcamp:cache
          file: docker/production/Dockerfile
          push: true
          tags: uwcsclub/codey-bootcamp:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Pull image and start container in deploy host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /codey/bootcamp
            docker pull uwcsclub/codey-bootcamp:latest
            docker-compose down
            docker-compose up -d
